import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import Sidebar from "~/components/Sidebar";
import Links from "~/components/Links";

const robotoSerif = Roboto_Serif({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${robotoSerif.className}`}>
        <Links />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
